# import smtplib
# from email.mime.multipart import MIMEMultipart
# from email.mime.text import MIMEText
# from datetime import datetime


# class EmailReport:

#     def __init__(self, sender_email, sender_password):
#         self.sender_email = sender_email
#         self.sender_password = sender_password

#     def generate_html(self, health_report):

#         current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

#         rows = ""

#         for ne, data in health_report.items():

#             status = data["Health Status"]

#             if status == "HEALTHY":
#                 color = "green"
#             elif status == "WARNING":
#                 color = "orange"
#             else:
#                 color = "red"

#             rows += f"""
#             <tr>
#                 <td>{ne}</td>
#                 <td>{data['Peak Traffic (MB)']}</td>
#                 <td>{data['Peak Time']}</td>
#                 <td>{data['Utilization %']}%</td>
#                 <td style='color:{color}; font-weight:bold;'>{status}</td>
#             </tr>
#             """

#         html = f"""
#         <html>
#         <body style="font-family: Arial;">

#         <div style="text-align:center;">
#             <h2>TNM - Core Network</h2>
#             <p><strong>PS Core Health Report</strong></p>
#         </div>

#         <p><strong>Generated By:</strong> Fraser Msusa</p>
#         <p><strong>Generated On:</strong> {current_time}</p>

#         <table border="1" cellpadding="8" cellspacing="0" width="100%">
#             <tr style="background-color:#f2f2f2;">
#                 <th>NE Name</th>
#                 <th>Peak Traffic (MB)</th>
#                 <th>Peak Time</th>
#                 <th>Utilization %</th>
#                 <th>Health Status</th>
#             </tr>
#             {rows}
#         </table>

#         <br>
#         <p style="font-size:12px; color:gray;">
#         This is an automated report from Core Network Monitoring System.
#         </p>

#         </body>
#         </html>
#         """

#         return html

#     def send_email(self, recipient_email, health_report):

#         msg = MIMEMultipart("alternative")
#         msg["Subject"] = "TNM PS Core Health Report"
#         msg["From"] = self.sender_email
#         msg["To"] = recipient_email

#         html_content = self.generate_html(health_report)

#         msg.attach(MIMEText(html_content, "html"))

#         server = smtplib.SMTP("smtp.gmail.com", 587)
#         server.starttls()
#         server.login(self.sender_email, self.sender_password)
#         server.sendmail(self.sender_email, recipient_email, msg.as_string())
#         server.quit()

#         print("Email sent successfully!")

import smtplib
import os
import matplotlib.pyplot as plt
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.image import MIMEImage
from email.mime.base import MIMEBase
from email import encoders
from datetime import datetime


class EmailReport:

    def __init__(self, sender_email, sender_password):
        self.sender_email = sender_email
        self.sender_password = sender_password

    # ==============================
    # Generate Traffic Chart
    # ==============================
    def generate_chart(self, pivot_data):

        plt.figure(figsize=(10, 5))

        for column in pivot_data.columns:
            plt.plot(pivot_data.index, pivot_data[column], label=column)

        plt.xlabel("Time")
        plt.ylabel("Traffic (MB)")
        plt.title("4G Data Traffic Trend - VDGW")
        plt.legend()
        plt.xticks(rotation=45)
        plt.tight_layout()

        chart_path = "traffic_chart.png"
        plt.savefig(chart_path)
        plt.close()

        return chart_path

    # ==============================
    # Generate HTML Report
    # ==============================
    def generate_html(self, health_report):

        current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        rows = ""

        for ne, data in health_report.items():

            status = data["Health Status"]

            if status == "HEALTHY":
                color = "#28a745"
            elif status == "WARNING":
                color = "#ffc107"
            else:
                color = "#dc3545"

            rows += f"""
            <tr>
                <td>{ne}</td>
                <td>{data['Peak Traffic (MB)']}</td>
                <td>{data['Peak Time']}</td>
                <td>{data['Utilization %']}%</td>
                <td style='color:{color}; font-weight:bold;'>{status}</td>
            </tr>
            """

        html = f"""
        <html>
        <body style="font-family: Arial;">

        <div style="text-align:center;">
            <h2 style="color:#003366;">TNM - Core Network</h2>
            <h3>PS Core Health Report</h3>
        </div>

        <p><strong>Generated By:</strong> Fraser Msusa</p>
        <p><strong>Generated On:</strong> {current_time}</p>

        <table border="1" cellpadding="8" cellspacing="0" width="100%">
            <tr style="background-color:#f2f2f2;">
                <th>NE Name</th>
                <th>Peak Traffic (MB)</th>
                <th>Peak Time</th>
                <th>Utilization %</th>
                <th>Health Status</th>
            </tr>
            {rows}
        </table>

        <br>
        <h3>Traffic Trend</h3>
        <img src="cid:traffic_chart">

        <br><br>
        <p style="font-size:12px; color:gray;">
        Automated report from Core Network Monitoring System.
        </p>

        </body>
        </html>
        """

        return html

    # ==============================
    # Send Email
    # ==============================
    def send_email(self, recipients, health_report, pivot_data, attachment_path):

        msg = MIMEMultipart("related")
        msg["Subject"] = "TNM PS Core Health Report"
        msg["From"] = self.sender_email
        msg["To"] = ", ".join(recipients)

        # Generate chart
        chart_path = self.generate_chart(pivot_data)

        # Attach HTML
        html_content = self.generate_html(health_report)
        msg.attach(MIMEText(html_content, "html"))

        # Attach chart inline
        with open(chart_path, "rb") as f:
            img = MIMEImage(f.read())
            img.add_header("Content-ID", "<traffic_chart>")
            msg.attach(img)

        # Attach CSV file
        with open(attachment_path, "rb") as f:
            part = MIMEBase("application", "octet-stream")
            part.set_payload(f.read())

        encoders.encode_base64(part)
        part.add_header(
            "Content-Disposition",
            f"attachment; filename={os.path.basename(attachment_path)}",
        )
        msg.attach(part)

        # Secure SSL connection
        server = smtplib.SMTP_SSL("smtp.gmail.com", 465)
        server.login(self.sender_email, self.sender_password)
        server.sendmail(self.sender_email, recipients, msg.as_string())
        server.quit()

        print("Professional email sent successfully!")