import smtplib
import os
import matplotlib.pyplot as plt
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.image import MIMEImage
from email.mime.base import MIMEBase
from email import encoders
from datetime import datetime


class EmailReport:

    def __init__(self, sender_email, sender_password):
        self.sender_email = sender_email
        self.sender_password = sender_password

    # Generate graph
    def generate_graph(self, pivot_data, kpi_name, output_file):

        plt.figure(figsize=(14,6))

        for i, column in enumerate(pivot_data.columns):


            if i == 0:
                color = "#007dff"  # 007dff
            else:
                color = "#41ba41"  # 41ba41

            plt.plot(
                pivot_data.index,
                pivot_data[column],
                color=color,
                marker='o',
                linewidth=2,
                markersize=4,
                markerfacecolor="white",     # white center
                markeredgecolor=color,       # border same as line
                markeredgewidth=2,
                label=column
            )
            
    #     plt.plot(
    #     pivot_data.index,
    #     pivot_data[column],
    #     color=color,
    #     marker='o',
    #     linewidth=2,
    #     markersize=4,
    #     markerfacecolor="white",     # white center
    #     markeredgecolor=color,       # border same as line
    #     markeredgewidth=2,
    #     label=column
    # )

        plt.title(kpi_name)
        plt.xlabel("Time")
        plt.ylabel("Traffic")
        plt.legend()
        plt.grid(True)

        plt.xticks(rotation=45)

        plt.tight_layout()
        plt.savefig(output_file)
        plt.close()


    # Generate all charts
    def generate_charts(self, processor):

        kpis = [
            "PGW-U 2/3G Gi traffic in MB (MB)",
            "4G Data traffic VDGW(CLOUD) (MB)",
            "PGW-U 2/3G Gn peak throughput in MB/s (MB/s)",
            "User Plane SGi downlink user traffic peak throughput in MB/s (MB/s) (MB/s)"
        ]

        chart_files = []

        for i, kpi in enumerate(kpis, start=1):

            pivot_data = processor.pivot_kpi(kpi)

            output_file = f"chart_{i}.png"

            self.generate_graph(pivot_data, kpi, output_file)

            chart_files.append(output_file)

        return chart_files


    # Generate HTML email
    def generate_html(self, health_report):

        current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        rows = ""

        for ne, data in health_report.items():

            status = data["Health Status"]

            if status == "HEALTHY":
                color = "#28a745"
            elif status == "WARNING":
                color = "#ffc107"
            else:
                color = "#dc3545"

            rows += f"""
            <tr>
                <td>{ne}</td>
                <td>{data['Peak Traffic (MB)']}</td>
                <td>{data['Peak Time']}</td>
                <td>{data['Utilization %']}%</td>
                <td style='color:{color}; font-weight:bold;'>{status}</td>
            </tr>
            """

        html = f"""
        <html>
        <body style="font-family: Arial;">

        <div style="text-align:center;">
            <h2 style="color:#003366;">TNM - Core Network</h2>
            <h3>PS Core Health Report</h3>
        </div>

        <p><strong>Generated By:</strong> Fraser Msusa</p>
        <p><strong>Generated On:</strong> {current_time}</p>

        <table border="1" cellpadding="8" cellspacing="0" width="100%">
            <tr style="background-color:#f2f2f2;">
                <th>NE Name</th>
                <th>Peak Traffic (MB)</th>
                <th>Peak Time</th>
                <th>Utilization %</th>
                <th>Health Status</th>
            </tr>
            {rows}
        </table>

        <br>
        <h3>Traffic Trend Charts</h3>

        <h4>1. PGW-U 2/3G Gi Traffic</h4>
        <img src="cid:chart_1"><br><br>

        <h4>2. 4G Data Traffic VDGW</h4>
        <img src="cid:chart_2"><br><br>

        <h4>3. PGW-U 2/3G Gn Peak Throughput</h4>
        <img src="cid:chart_3"><br><br>

        <h4>4. SGi Downlink Peak Throughput</h4>
        <img src="cid:chart_4"><br><br>

        </body>
        </html>
        """

        return html


    # Send email
    def send_email(self, recipients, health_report, processor, attachment_path):

        msg = MIMEMultipart("related")
        msg["Subject"] = "TNM PS Core Health Report"
        msg["From"] = self.sender_email
        msg["To"] = ", ".join(recipients)

        chart_files = self.generate_charts(processor)

        html_content = self.generate_html(health_report)
        msg.attach(MIMEText(html_content, "html"))

        # attach charts
        for i, chart in enumerate(chart_files, start=1):

            with open(chart, "rb") as f:
                img = MIMEImage(f.read())

            img.add_header("Content-ID", f"<chart_{i}>")

            msg.attach(img)

        # attach csv
        with open(attachment_path, "rb") as f:
            part = MIMEBase("application", "octet-stream")
            part.set_payload(f.read())

        encoders.encode_base64(part)

        part.add_header(
            "Content-Disposition",
            f"attachment; filename={os.path.basename(attachment_path)}"
        )

        msg.attach(part)

        server = smtplib.SMTP_SSL("smtp.gmail.com", 465)
        server.login(self.sender_email, self.sender_password)

        server.sendmail(self.sender_email, recipients, msg.as_string())

        server.quit()

        print("Email with charts sent successfully!")