import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime


class EmailReport:

    def __init__(self, sender_email, sender_password):
        self.sender_email = sender_email
        self.sender_password = sender_password

    def generate_html(self, health_report):

        current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        rows = ""

        for ne, data in health_report.items():

            status = data["Health Status"]

            if status == "HEALTHY":
                color = "green"
            elif status == "WARNING":
                color = "orange"
            else:
                color = "red"

            rows += f"""
            <tr>
                <td>{ne}</td>
                <td>{data['Peak Traffic (MB)']}</td>
                <td>{data['Peak Time']}</td>
                <td>{data['Utilization %']}%</td>
                <td style='color:{color}; font-weight:bold;'>{status}</td>
            </tr>
            """

        html = f"""
        <html>
        <body style="font-family: Arial;">

        <div style="text-align:center;">
            <h2>TNM - Core Network</h2>
            <p><strong>PS Core Health Report</strong></p>
        </div>

        <p><strong>Generated By:</strong> Fraser Msusa</p>
        <p><strong>Generated On:</strong> {current_time}</p>

        <table border="1" cellpadding="8" cellspacing="0" width="100%">
            <tr style="background-color:#f2f2f2;">
                <th>NE Name</th>
                <th>Peak Traffic (MB)</th>
                <th>Peak Time</th>
                <th>Utilization %</th>
                <th>Health Status</th>
            </tr>
            {rows}
        </table>

        <br>
        <p style="font-size:12px; color:gray;">
        This is an automated report from Core Network Monitoring System.
        </p>

        </body>
        </html>
        """

        return html

    def send_email(self, recipient_email, health_report):

        msg = MIMEMultipart("alternative")
        msg["Subject"] = "TNM PS Core Health Report"
        msg["From"] = self.sender_email
        msg["To"] = recipient_email

        html_content = self.generate_html(health_report)

        msg.attach(MIMEText(html_content, "html"))

        server = smtplib.SMTP("smtp.gmail.com", 587)
        server.starttls()
        server.login(self.sender_email, self.sender_password)
        server.sendmail(self.sender_email, recipient_email, msg.as_string())
        server.quit()

        print("Email sent successfully!")