from openpyxl import Workbook
from openpyxl.styles import Font, Alignment
from openpyxl.drawing.image import Image
from datetime import datetime

class ExcelReport:

    def __init__(self, generator_name="Fraser Msusa"):
        self.generator_name = generator_name

    def create_report(self, chart_paths, health_report, output_file):

        wb = Workbook()
        ws = wb.active
        ws.title = "Weekly Traffic Trends"

        # ===== TITLE =====
        ws["A1"] = "TNM - Core Network"
        ws["A1"].font = Font(size=16, bold=True)

        ws["A2"] = "PS Core Health Report"
        ws["A2"].font = Font(size=14, bold=True)

        ws["A3"] = f"Generated By: {self.generator_name}"
        ws["A4"] = f"Generated On: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"

        row = 6

        titles = [
            "PGW-U 2/3G Gi Traffic",
            "4G Data Traffic VDGW(CLOUD)",
            "PGW-U 2/3G Gn Peak Throughput",
            "User Plane SGi Downlink Peak Throughput"
        ]

        # ===== INSERT CHARTS =====
        for i, chart in enumerate(chart_paths):

            ws[f"A{row}"] = titles[i]
            ws[f"A{row}"].font = Font(bold=True)

            row += 1

            img = Image(chart)
            img.width = 900
            img.height = 400

            ws.add_image(img, f"A{row}")

            row += 22

        # ===== HEALTH SUMMARY =====
        ws[f"A{row}"] = "Health Summary"
        ws[f"A{row}"].font = Font(size=13, bold=True)

        row += 2

        headers = [
            "NE Name",
            "Peak Traffic (MB)",
            "Peak Time",
            "Minimum Traffic",
            "Minimum Time",
            "Average Traffic",
            "Utilization %",
            "Health Status"
        ]

        for col, header in enumerate(headers, start=1):
            cell = ws.cell(row=row, column=col)
            cell.value = header
            cell.font = Font(bold=True)
            cell.alignment = Alignment(horizontal="center")

        row += 1

        for ne, data in health_report.items():

            ws.cell(row=row, column=1).value = ne
            ws.cell(row=row, column=2).value = data["Peak Traffic (MB)"]
            ws.cell(row=row, column=3).value = str(data["Peak Time"])
            ws.cell(row=row, column=4).value = data["Minimum Traffic (MB)"]
            ws.cell(row=row, column=5).value = str(data["Minimum Time"])
            ws.cell(row=row, column=6).value = data["Average Traffic (MB)"]
            ws.cell(row=row, column=7).value = data["Utilization %"]
            ws.cell(row=row, column=8).value = data["Health Status"]

            row += 1

        wb.save(output_file)

        print("Excel report generated successfully!")